
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import c3po.*;
import java.io.Reader;
import java.io.StringReader;
import java.util.*;

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        compileButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        diagnosticTextArea = new javax.swing.JTextArea();
        assemblyTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        final int fontSize = 14;

        inputTextArea.setColumns(20);
        inputTextArea.setFont(new java.awt.Font("Segoe UI", 0, fontSize)); // NOI18N
        inputTextArea.setRows(5);
        jScrollPane1.setViewportView(inputTextArea);

        compileButton.setFont(new java.awt.Font("Segoe UI", 0, fontSize)); // NOI18N
        compileButton.setText("Compilar");
        compileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileButtonActionPerformed(evt);
            }
        });

        diagnosticTextArea.setColumns(20);
        diagnosticTextArea.setFont(new java.awt.Font("Segoe UI", 0, fontSize)); // NOI18N
        diagnosticTextArea.setRows(5);
        jScrollPane2.setViewportView(diagnosticTextArea);

        assemblyTextArea.setColumns(20);
        assemblyTextArea.setFont(new java.awt.Font("Segoe UI", 0, fontSize)); // NOI18N
        assemblyTextArea.setRows(5);
        jScrollPane3.setViewportView(assemblyTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(49, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 309,
                                                                Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2)
                                                        .addComponent(jScrollPane3))
                                                .addGap(42, 42, 42))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(compileButton)
                                                        .addGap(145, 145, 145)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(compileButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compileButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_compileButtonActionPerformed

        var sourceFile = inputTextArea.getText();
        String source = "\n{\n";
        source += sourceFile;
        source += "\n}\n";

        try {
            var tokens = Lexer.tokenize(source, true);
            var ast = Parser.parse(tokens.toArray(new Token[tokens.size()]));//
			((Scope)ast).initAsGlobalScope();

            ast.check(null);

            var root = (Scope)ast;
            var builder = new IRBuilder();

            root.genIR(null, builder);
            var prog = builder.build();
            System.out.println(prog);

            var asmBuilder = new AssemblyBuilder(prog);
            var asmSource = asmBuilder.build();
            assemblyTextArea.setText(asmSource);
            diagnosticTextArea.setText("FOI!!");
        } catch (LanguageException e) {
            diagnosticTextArea.setText(e.toString());
            // System.err.println(e.toString());
            // System.exit(1);
        }

    }// GEN-LAST:event_compileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compileButton;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea diagnosticTextArea;
    private javax.swing.JTextArea assemblyTextArea;
    // End of variables declaration//GEN-END:variables
};
