/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import c3po.*;
import java.io.Reader;
import java.io.StringReader;

/**
 *
 * @author joao_
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        assemblyTextArea = new javax.swing.JTextArea();
        compileButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        diagnosticTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        assemblyTextArea.setEditable(false);
        assemblyTextArea.setColumns(20);
        assemblyTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        assemblyTextArea.setRows(5);
        jScrollPane1.setViewportView(assemblyTextArea);

        compileButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        compileButton.setText("Compilar");
        compileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileButtonActionPerformed(evt);
            }
        });

        diagnosticTextArea.setEditable(false);
        diagnosticTextArea.setColumns(20);
        diagnosticTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diagnosticTextArea.setRows(5);
        jScrollPane2.setViewportView(diagnosticTextArea);

        inputTextArea.setColumns(20);
        inputTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputTextArea.setRows(5);
        jScrollPane4.setViewportView(inputTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 637,
                                                Short.MAX_VALUE)
                                        .addComponent(compileButton)
                                        .addComponent(jScrollPane4))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 424,
                                                        Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(compileButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));

        pack();
    }// </editor-fold>

    private void compileButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_compileButtonActionPerformed

        var sourceFile = inputTextArea.getText();
        String source = "\n{\n";
        source += sourceFile;
        source += "\n}\n";

        try {
            var tokens = Lexer.tokenize(source, true);
            var ast = Parser.parse(tokens.toArray(new Token[tokens.size()]));//
            ((Scope) ast).initAsGlobalScope();

            ast.check(null);

            var root = (Scope) ast;
            var builder = new IRBuilder();

            root.genIR(null, builder);
            var prog = builder.build();
            System.out.println(prog);

            var asmBuilder = new AssemblyBuilder(prog);
            var asmSource = asmBuilder.build();
            assemblyTextArea.setText(asmSource);
            diagnosticTextArea.setText("Compiled with success");
        } catch (LanguageException e) {
            diagnosticTextArea.setText(e.toString());
            // System.err.println(e.toString());
            // System.exit(1);
        }

    }// GEN-LAST:event_compileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    };

    // Variables declaration - do not modify
    private javax.swing.JTextArea assemblyTextArea;
    private javax.swing.JButton compileButton;
    private javax.swing.JTextArea diagnosticTextArea;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration
};